import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  // Theme Toggle
  themeToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    borderRadius: 12,
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  navIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: "none",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  // Home
  homeContainer: {
    minHeight: "100vh",
    background: "radial-gradient(circle at top left, #ffffff 0%, #f8fafc 100%)",
    position: "relative",
    overflow: "hidden",
  },
  bgDecor1: {
    position: "absolute",
    top: -200,
    right: -200,
    width: 600,
    height: 600,
    background: "radial-gradient(circle, rgba(16, 185, 129, 0.08) 0%, transparent 70%)",
    borderRadius: "50%",
    filter: "blur(60px)",
  },
  bgDecor2: {
    position: "absolute",
    bottom: -150,
    left: -150,
    width: 500,
    height: 500,
    background: "radial-gradient(circle, rgba(20, 184, 166, 0.08) 0%, transparent 70%)",
    borderRadius: "50%",
    filter: "blur(50px)",
  },
  homeHeader: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    padding: "24px 40px",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    zIndex: 100,
    backdropFilter: "blur(12px)",
    background: "rgba(255, 255, 255, 0.5)",
    borderBottom: "1px solid rgba(0, 0, 0, 0.05)",
  },
  adminLink: {
    background: "linear-gradient(135deg, #059669, #0d9488)",
    border: "none",
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    padding: "12px 28px",
    borderRadius: 30,
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 8px 20px rgba(5, 150, 105, 0.25)",
    letterSpacing: "0.025em",
  },
  heroSection: {
    textAlign: "center",
    marginBottom: 80,
    padding: "0 24px",
    position: "relative",
  },
  heroTitle: {
    fontSize: "clamp(56px, 12vw, 100px)",
    fontWeight: 900,
    color: "#0f172a",
    margin: 0,
    lineHeight: 0.95,
    letterSpacing: "-0.04em",
    position: "relative",
  },
  heroTitleAccent: {
    background: "linear-gradient(135deg, #059669 0%, #10b981 50%, #14b8a6 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  heroSubtitle: {
    fontSize: 18,
    color: "#64748b",
    marginTop: 24,
    fontWeight: 500,
    letterSpacing: "0.4em",
    textTransform: "uppercase",
  },
  heroDivider: {
    width: 80,
    height: 4,
    background: "linear-gradient(90deg, #059669, #14b8a6)",
    margin: "32px auto 0",
    borderRadius: 4,
    opacity: 0.8,
  },
  sectionsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 32,
    maxWidth: 1100,
    width: "100%",
    padding: "0 24px",
  },
  sectionCard: {
    background: "rgba(255, 255, 255, 0.8)",
    backdropFilter: "blur(8px)",
    borderRadius: 28,
    padding: "48px 32px",
    textAlign: "center",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
  },
  sectionIcon: {
    fontSize: 56,
    display: "block",
    marginBottom: 24,
    filter: "drop-shadow(0 10px 15px rgba(0, 0, 0, 0.1))",
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#1e293b",
    margin: "0 0 12px",
    letterSpacing: "-0.02em",
  },
  sectionDesc: {
    color: "#64748b",
    fontSize: 15,
    margin: "0 0 24px",
    lineHeight: 1.7,
  },
  comingSoon: {
    display: "inline-block",
    background: "rgba(5, 150, 105, 0.08)",
    color: "#059669",
    fontSize: 12,
    fontWeight: 700,
    padding: "8px 20px",
    borderRadius: 20,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    border: "1px solid rgba(5, 150, 105, 0.15)",
  },

  // Dashboard
  dashContainer: {
    minHeight: "100vh",
    background: "#f8fafc",
    position: "relative",
  },
  dashHeader: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(20px)",
    borderBottom: "1px solid rgba(0, 0, 0, 0.05)",
    padding: "24px 40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  dashName: {
    fontSize: 32,
    fontWeight: 900,
    background: "linear-gradient(135deg, #0f172a 0%, #334155 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    margin: 0,
    letterSpacing: "-0.04em",
  },
  dashMain: {
    maxWidth: 1200,
    margin: "0 auto",
    padding: "80px 32px 140px",
  },
  dashSubtext: {
    color: "#64748b",
    fontSize: 20,
    textAlign: "center",
    marginBottom: 64,
    fontWeight: 400,
  },
  dashCard: {
    background: "#fff",
    border: "1px solid #f1f5f9",
    borderRadius: 32,
    padding: 48,
    cursor: "pointer",
    textAlign: "center",
    transition: "all 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.05)",
  },
  cardIconWrap: {
    width: 84,
    height: 84,
    borderRadius: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 28,
    color: "#fff",
    boxShadow: "0 20px 40px -10px rgba(5, 150, 105, 0.3)",
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: 800,
    color: "#0f172a",
    margin: "0 0 12px",
    letterSpacing: "-0.02em",
  },
  cardDesc: {
    fontSize: 16,
    color: "#64748b",
    margin: 0,
    lineHeight: 1.6,
  },

  // Sidebar
  sidebar: {
    width: 300,
    background: "#fff",
    borderRight: "1px solid #f1f5f9",
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    position: "fixed",
    left: 0,
    top: 0,
    zIndex: 1000,
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarHeader: {
    padding: "32px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  folderItem: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "14px 20px",
    borderRadius: 16,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
    border: "1px solid transparent",
    width: "100%",
    textAlign: "left",
  },
  addFolderBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    background: "linear-gradient(135deg, #059669, #10b981)",
    border: "none",
    color: "#fff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 12px rgba(5, 150, 105, 0.2)",
    transition: "all 0.3s ease",
  },

  // Shared UI
  addItemBtn: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 28px",
    background: "linear-gradient(135deg, #059669, #10b981)",
    border: "none",
    color: "#fff",
    borderRadius: 16,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 10px 25px -5px rgba(5, 150, 105, 0.3)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    letterSpacing: "0.01em",
  },
  backBtn: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 20px",
    background: "#fff",
    border: "1.5px solid #e2e8f0",
    color: "#475569",
    borderRadius: 14,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  itemCard: {
    background: "#fff",
    borderRadius: 24,
    padding: "28px 32px",
    border: "1px solid #f1f5f9",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    width: "100%",
    textAlign: "left",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.03)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.4)",
    backdropFilter: "blur(12px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
    padding: 24,
  },
  modal: {
    background: "#fff",
    borderRadius: 32,
    padding: 48,
    maxWidth: 480,
    width: "100%",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  input: {
    padding: "16px 20px",
    fontSize: 16,
    border: "2px solid #f1f5f9",
    borderRadius: 16,
    background: "#f8fafc",
    color: "#0f172a",
    outline: "none",
    transition: "all 0.3s ease",
    width: "100%",
    boxSizing: "border-box",
  },
};
